In [9]:
import pandas as pd
fileaaa = pd.read_csv('/run/media/penglab/72D4-8C3C/18454_00129_ZFY_SYY_DYJ_YLL_stamp_2019_09_25_17_23.ano.eswc',
                      skiprows=[0,1,2],names=['n','type',' x',' y','z','radius', 'parent', 'seg_id', 'level', 'mode', 'timestamp', 'TFresindex'],sep = '\s+')

In [12]:
import numpy as np
region_ori, count_ori = np.unique(fileaaa['seg_id'], return_counts=True)
print(region_ori)
print(count_ori)


[0]
[36570]


In [13]:
region_ori, count_ori = np.unique(fileaaa['level'], return_counts=True)
print(region_ori)
print(count_ori)


[  0   1   2 618]
[ 5957 30073   410   130]


In [14]:
region_ori, count_ori = np.unique(fileaaa['mode'], return_counts=True)
print(region_ori)
print(count_ori)


[-2147483648 -2139095040 -2130706432 -2122317824 -2113929216 -2105540608
 -2088763392 -2080374784 -2071986176 -2063597568 -2055208960 -2046820352
 -2038431744 -2030043136 -2021654528 -2013265920 -2004877312 -1996488704
 -1988100096 -1979711488 -1971322880 -1962934272 -1954545664 -1946157056
 -1937768448 -1929379840 -1920991232 -1912602624 -1904214016 -1895825408
 -1887436800 -1870659584 -1862270976 -1853882368 -1845493760 -1837105152
 -1828716544 -1820327936 -1811939328 -1803550720 -1795162112 -1786773504
 -1778384896 -1769996288 -1761607680 -1753219072 -1744830464 -1736441856
 -1728053248 -1719664640 -1711276032 -1702887424 -1694498816 -1686110208
 -1677721600 -1669332992 -1660944384 -1652555776 -1644167168 -1635778560
 -1627389952 -1619001344 -1610612736 -1602224128 -1593835520 -1585446912
 -1577058304 -1568669696 -1560281088 -1551892480 -1543503872 -1535115264
 -1526726656 -1518338048 -1501560832 -1493172224 -1484783616 -1476395008
 -1468006400 -1459617792 -1451229184 -1442840576 -1

In [15]:
region_ori, count_ori = np.unique(fileaaa['timestamp'], return_counts=True)
print(region_ori)
print(count_ori)


[0 1 2 4]
[23388 12989   148    45]


In [16]:
region_ori, count_ori = np.unique(fileaaa['TFresindex'], return_counts=True)
print(region_ori)
print(count_ori)

[1632018448]
[36570]
